import { dowmvideo } from "../utils/index.js";
import fetch from "node-fetch";
let jslist = {
    "j": "鸡",
    "n": "你",
    "t": "太",
    "m": "美",
    "c1": "唱",
    "t1": "跳",
    "rp": "rap",
    "lq": "篮球",
    "mck": "music",
    "xs": "笑死",
    "t2": "哇呵呵",
    "t3": "喜欢",
    "qm": "制作人",
    "djh": "大家好",
    "ws": "我是",
    "ngm": "你干嘛~",
    "hh": "哈哈",
    "ay": "哎哟",
    "nhf": "你好烦~",
    "jntm": "开始吟唱",
    "ngmhhy": "你干嘛哈哈哟",
    "yhhmgn": "哟哈哈嘛干你",
    "esj": "二手鸡",
    "rup": "rap鸡",
    "djj": "DJ鸡",
    "xxj": "谢谢鸡",
    "jhj": "惊魂鸡",
    "xjj": "仙剑鸡",
    "xnj": "新年鸡",
    "zdj": "战斗鸡",
    "thj": "桃花鸡",
    "mrj": "某人鸡",
    "jnj": "江南鸡",
    "jjj": "尖叫鸡",
    "bbj": "baby鸡",
    "hxj": "欢喜鸡",
    "yyj": "耶耶鸡",
    "jtm": "鸡太美"
}
